### ISSUE TITLE
Me da un error 

### ISSUE THREAD

**Issue by jjcortes** [spatialstatisticsupna/Mmodels_SERRA_article#1]
Hola,
Tengo un problema al ejecutar vuestro script.
$ Rscript  reproduce_paper_Mmodels.R 
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
Loading required package: Matrix
Loading required package: parallel
Loading required package: foreach
This is INLA_20.03.17 built 2020-09-10 10:29:46 UTC.
See www.r-inla.org/contact-us for how to get help.
To enable PARDISO sparse library; see inla.pardiso()
Error in readChar(con, 5L, useBytes = TRUE) : 
  no se puede abrir la conexión
Calls: load -> readChar
Además: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'resul/resulta_inla_bym_fe.RData', probable reason 'No existe el archivo o el directorio'
Ejecución interrumpida

¿Alguna solución?

Saludos.

**Comment by GonzaloVicente** [comment]
Buenos días,
En R-4.0.2 ha habido unos cambios internos que puede hacer que los modelos se bloqueen
Estamos trabajando en eso y próximamente lo actualizaremos.
Sin embargo, este no es su problema. 

De acuerdo a su versión de INLA, entiendo que su versión de R es R-3.6.3 o anterior.
En estas versiones, el Script 'reproduce_paper_Mmodels.R' debe funcionar sin problemas (lo he chequeado al recibir su comentario). 
Sin embargo, es necesario obtener los resultados de los distintos modelos antes de poder ejecutar el Script 'reproduce_paper_Mmodels.R'. 

Su mensaje de error (corresponde a la línea 82 del código): 
cannot open compressed file 'resul/resulta_inla_bym_fe.RData', probable reason 'No existe el archivo o el directorio'

indica que no tiene al archivo 'resulta_inla_bym_fe.RData', para obtenerlo es preciso ejecutar 'run_inla_bym_fe.R'. 

Saludos
Gonzalo Vicente
